### ISSUE TITLE
Breaking changes in CodeGen master

### ISSUE THREAD

**Issue by amellnik** [tshort/ExportWebAssembly.jl#4]
I think https://github.com/tshort/CodeGen.jl/commit/ca90519d3851c31290f06cb30f2316c8accfc828 breaks `irgen` here, will try to take a look in the next few days.

**Comment by tshort** [comment]
I'm sure you're right, @amellnik. I have not kept CodeGen and ExportWebAssembly in sync. I can't look until at least this weekend.

**Comment by tshort** [comment]
I've made some progressd on this. I fixed the `irgen` issue and got the docker setup working again. 

It still doesn't create runnable code for some of the code from CodeGen that worked earlier (this [works](https://github.com/tshort/ExportWebAssembly.jl/blob/codegen-jl/test/runtests.jl#L11); this is [broken](https://github.com/tshort/ExportWebAssembly.jl/blob/codegen-jl/test/runtests.jl#L15)). I may have to backtrack to try to fix things.

In hindsight, I should have kept other things together at least until things start to work better.

**Comment by amellnik** [comment]
Looks good!  

Edit2: It looks like `export_js` needs to be run in `/libs` -- is that also the case for you?

**Comment by tshort** [comment]
CodeGen is in better shape. It gets all the way through its tests with `LLVM.verify` done on the modules created. 

CodeGen and ExportWebAssembly are in sync.

On running `export_js`, I need to be in the directory with the `*.bc` files, but that's `/work` for me. 

Things are still broken for me. Locally, I can get code to compile to JS, but it fails in nodejs as follows:
```
$ node
> a=require("./array_max.js")
[Emscripten Module object]
> a._init_julia_()
Thrown: Assertion failed: (jl_gc_sizeclasses[i] < 16 && jl_gc_sizeclasses[i] % sizeof(void*) == 0) || (jl_gc_sizeclasses[i] % 16 == 0), at: gc.c,2691,jl_init_thread_heap at Error
    at jsStackTrace (/mnt/raid/e/tmp/jl/array_max.js:1053:13)
    at stackTrace (/mnt/raid/e/tmp/jl/array_max.js:1070:12)
    at ___assert_fail (/mnt/raid/e/tmp/jl/array_max.js:1538:210)
    at _jl_init_thread_heap (/mnt/raid/e/tmp/jl/array_max.js:91503:3)
    at _ti_initthread (/mnt/raid/e/tmp/jl/array_max.js:91416:3)
    at _ti_init_master_thread (/mnt/raid/e/tmp/jl/array_max.js:91337:2)
    at _jl_init_threading (/mnt/raid/e/tmp/jl/array_max.js:90912:2)
    at _init_julia_ (/mnt/raid/e/tmp/jl/array_max.js:8199:2)
    at Object.asm._init_julia_ (/mnt/raid/e/tmp/jl/array_max.js:118204:28)
    at repl:1:3
```
This is for:
```julia
using ExportWebAssembly
array_max (generic function with 1 method)
write_js("array_max.js", array_max, Tuple{Int})
```
The code in Julia's `_init_julia` hasn't changed. Maybe something else has changed. I might need to try the "from-source" compilation again to make sure that the Julia binary and the *.bc files are in sync. Once we have a release of 0.7/1.0, this problem should go away (but that might be several months away).
